GET http://localhost:8080/api/v1/categories

###
GET http://localhost:8080/api/v1/categories/1

###
POST http://localhost:8080/api/v1/categories
Content-Type: application/json

{
    "category_name": "Electronics",
    "description": "Electronics description"
}

### update
PUT http://localhost:8080/api/v1/categories/1
Content-Type: application/json

{
    "id": 2,
    "name": "LG"
}
### delete
DELETE http://localhost:8080/api/v1/categories/3
Content-Type: application/json

