POST http://localhost:8080/api/v1/staffs
Content-Type: application/json

{
    "first_name": "Jasdhaisd",
    "last_name": "asd",
    "email": "joasda@doe.com",
    "active": true,
    "password": "00000000"
}


###
POST http://localhost:8080/api/v1/staffs
Content-Type: application/json

{
    "first_name": "admin",
    "last_name": "admin",
    "email": "admin@gmail.com",
    "password": "12345678",
    "active": true
}
###
POST http://localhost:8080/api/v1/staffs
 Content-Type: application/json

{
    "staff_name": "Jackie",
    "description":"Jackie description"
}

###
PUT http://localhost:8080/api/v1/staffs/67bc8346e5c85af294408f60
 Content-Type: application/json

{
    "staff_name": "Jackies",
    "description":"Jackies description"
}

###
DELETE http://localhost:8080/api/v1/staffs/67e0d2a89295f570ab9e0ea9
Content-Type: application/json